name: Mnet-Plus-Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *' # 每 15 分鐘執行一次

jobs:
  EL7ZUP-Bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run Python script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EL7ZUP_WEBHOOK: ${{ secrets.EL7ZUP_WEBHOOK }}
        UPDATED_AT: ${{ vars.UPDATED_AT }}
      run:
        python el7zup_bot.py
