name: Mnet-Plus-Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *' # 每 15 分鐘執行一次

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  EL7ZUP-Bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          envkey_FIREBASE_ADMIN_KEY: ${{ secrets.FIREBASE_ADMIN_KEY }}
          envkey_EL7ZUP_WEBHOOK: ${{ secrets.EL7ZUP_WEBHOOK }}
      - name: run Python script
        run: |
          python main.py